INSERT INTO producto (producto, descripcion, id_categoria, id_subcategoria, costo, precio) VALUES
('SMARTLINE020-4 panel incendio convencional INIM','PANEL CONVENCIONAL DETECCION DE INCENDIO 4 ZONAS EXPANDIBLE A 20 HASTA 32 DISPOSITIVOS POR ZONA, CUMPLIMIENTO EN54',NULL, NULL, 570550, 1),

('SMARTLETUSEE-LCD-LITE repetidor lcd panel incendio INIM','REPETIDOR LCD PARA CONTROL Y VISUALIZACION DE PANELES SMARTLINE CONVENCIONAL HASTA 4 POR PANEL',NULL, NULL, 582455, 1),

('SMARTLINE036-4 panel incendio convencional INIM', 'PANEL DETECCION INCENDIO CONVENCIONAL 4 ZONAS EXPANDIBLE HASTA 36 ZONAS MAX. 32 DISPOS. POR ZONA, CUMPLIMIENTO EN54', NULL, NULL, 848975, 1),

('PREVIDIA-M-EXP modulo expansor panel incendio INIM','MODULO EXPANSOR DE 8 ZONAS PARA PANEL PREVIDIA-MICRO-MSR + 6 TERMINALES + 1 I/O CONVENCIONAL',NULL, NULL, 175310, 1),

('PREVIDIA-MICRO-MSR panel incendio convencional INIM',
'PANEL CONVENCIONAL 4 ZONAS+4 TERMINALES+3 I/O EXPANDIBLE HORNET CON SERIE PREVIDIA APP CLOUD VIDEO VERIFICACION NOTIFICACIONES TOUCH',
NULL, NULL, 925250, 1),

('INFEIN4ASLINE8Z tarjeta expansion panel incendio INIM',
'TARJETA DE EXPANSION 8 ZONAS CON SALIDA SUPERVISADA PARA CENTRALES CONVENCIONALES',
NULL, NULL, 161635, 1),

('INFDIN4AID100 detector humo convencional INIM',
'DETECTOR DE HUMO OPTICO CONVENCIONAL SERIE IRIS SENSIBILIDAD CONFIGURABLE 0,08 - 0,15DB/M CUMPLIMIENTO EN54 Y UL PARA PANELES SMARTLINE',
NULL, NULL, 44735, 1),

('ID100 detector humo convencional INIM',
'DETECTOR DE HUMO OPTICO 2 HILOS CONVENCIONAL SERIE IRIS SENSIBILIDAD CONFIGURABLE 0,08 - 0,15DB/M CUMPLIMIENTO EN54 Y UL PARA PANELES SMARTLINE Y PREVIDIA MICRO',
NULL, NULL, 44735, 1),

('INFDIN4AID200 detector termico convencional INIM',
'DETECTOR TERMICO CONVENCIONAL SERIE IRIS SENSIBILIDAD CONFIGURABLE, CUMPLIMIENTO EN54 Y UL PARA PANELES SMARTLINE',
NULL, NULL, 45060, 1),

('ID200 detector termico convencional INIM',
'DETECTOR TERMICO 2 HILOS CONVENCIONAL SERIE IRIS SENSIBILIDAD CONFIGURABLE, CUMPLIMIENTO EN54 Y UL PARA PANELES SMARTLINE Y PREVIDIA MICRO',
NULL, NULL, 46060, 1),

('INFDIN4AID300 detector dual convencional INIM',
'DETECTOR OPTICO/TERMICO CONVENCIONAL SERIE IRIS SENSIBILIDAD Y MODO DE OPERACIÓN CONFIGURABLE, CUMPLIMIENTO EN54 Y UL PARA PANELES SMARTLINE',
NULL, NULL, 59755, 1),

('ID300 detector dual convencional INIM',
'DETECTOR OPTICO/TERMICO 2 HILOS CONVENCIONAL SERIE IRIS SENSIBILIDAD Y MODO DE OPERACIÓN CONFIGURABLE, CUMPLIMIENTO EN54 Y UL PARA PANELES SMARTLINE Y PREVIDIA MICRO',
NULL, NULL, 63665, 1),

('EB0010 base detector incendio INIM',
'BASE 2 HILOS BAJA PARA DETECTORES DE HUMO CONVENCIONALES Y DIRECCIONABLES, CUMPLIMIENTO EN54 Y UL',
NULL, NULL, 8090, 1),

('INFDIN4AEB0020 base con relevo detector INIM',
'BASE CON RELEVO (4 HILOS) PARA DETECTORES DE HUMO CONVENCIONALES Y DIRECCIONABLES, CUMPLIMIENTO EN54',
NULL, NULL, 19160, 1),

('EB0020 base con relevo detector INIM',
'BASE CON RELEVO (4 HILOS) PARA DETECTORES DE HUMO CONVENCIONALES Y DIRECCIONABLES, CUMPLIMIENTO EN54 Y UL',
NULL, NULL, 19800, 1),

('WCP0020 cubierta estacion manual INIM',
'CUBIERTA TRANSPARENTE PARA EVITAR ACTIVACION ACCIDENTAL COMPATIBLE CON PULSADORES EC0020 E IC0020',
NULL, NULL, 3900, 1),

('IC0020 estacion manual incendio INIM',
'ESTACION MANUAL (PULSADOR) DE ALARMA CONVENCIONAL PARA INCENDIO RESTAURABLE COLOR ROJO, CUMPLIMIENTO EN54, PARA PANELES SMARTLINE Y PREVIDIA MICRO',
NULL, NULL, 46170, 1),

('SMARTYGFR sirena convencional incendio INIM',
'SIRENA CONVENSIONAL 110DB A 1M PARA INTERIOR DE COLOR ROJO INDICADOR LUMINOSO LED BLANCO ALIMENTACION 24VDC IP31, CUMPLIMIENTO EN54 PARA PANELES SMARTLINE Y PREVIDIA MICRO',
NULL, NULL, 71040, 1),

('IS2021RE sirena estroboscopica convencional INIM',
'SIRENA OPTICO ACUSTICA CONVENCIONAL ROJA INSLATACION A PARED, POTENCIA 101DB, PARA INTERIOR Y EXTERIOR  IP65, CUMPLIMIENTO EN54, PARA PANELES SMARTLINE Y PREVIDIA MICRO',
NULL, NULL, 143835, 1),

('IS2050RE sirena voz convencional INIM',
'SIRENA CONVENCIONAL CON FLASH (TIPO LED) Y EMISION DE 16 MENSAJES DE VOZ SELECCIONABLE CON HERRAMIENTRA ITK2000  IP65 EN54',
NULL, NULL, 210535, 1),

('SMARTLETLOOSE1 tarjeta extincion incendio INIM',
'TARJETA PARA CONTROL DE 1 CANAL DE EXTINCION POR GAS (AGENTE LIMPIO) COMPATIBLE CON PANELES SMARTLINE O SMARTLIGHT',
NULL, NULL, 422095, 1),

('PREVIDIA-C050SR panel incendio direccionable INIM',
'PANEL DETECCION DE INCENDIO DIRECCIONABLE 1 BUCLE HASTA 64 DISPOSITIVOS GABINETE PEQUEÑO ROJO, INCLUYE APP PARA MONITOREO Y CONTROL REMOTO CUMPLIMIENTO EN54',
NULL, NULL, 1884705, 1),

('PREVIDIA-C100SR panel incendio direccionable INIM',
'PANEL DIRECCIONABLE DETECCION DE INCENDIO 1 BUCLE HASTA 240 DISPOSITIVOS EN54 PANTALLA TACTIL. INCLUYE  APP PARA MONITOREO Y CONTROL REMOTO, CUMPLIMIENTO EN54',
NULL, NULL, 2248145, 1),

('PREVIDIA-C200LR panel incendio direccionable INIM',
'PANEL DETECCION DE INCENDIO DIRECCIONABLE 2 BUCLES HASTA 240 DISPOSITIVOS GABINETE GRANDE ROJO CERTIFICACION UL Y EN54',
NULL, NULL, 3238725, 1),

('PREVIDIA216R panel incendio modular INIM',
'PANEL DIRECCIONABLE DETECCION Y EXTINCIÓN INCENDIO CRECIMIENTO MODULAR, INCLUYE 2 BUCLES EXPANDIBLE A 16. CAPACIDAD DE 240 DISPOSITIVOS DIRECCIONABLES POR BUCLE, GABINETE ROJO, CERTIFICACION UL Y EN54',
NULL, NULL, 4387935, 1),

('DELF165-6PP parlante audio evacuacion INIM',
'PARLANTE 6,5\" PARA AUDIO EVACUACION 6 W-100V PARA MONTAJE EN FALSO TECHO (EMPOTRAR) (ALTAVOZ-SPEAKER)',
NULL, NULL, 141835, 1),

('DAL165-6PP parlante audio evacuacion INIM',
'PARLANTE 6,5\" PARA AUDIO EVACUACION 6 W-100V PARA MONTAJE EN TECHO / PARED (SOBREPONER) (ALTAVOZ-SPEAKER)',
NULL, NULL, 150930, 1);

INSERT INTO producto (producto, descripcion, id_categoria, id_subcategoria, costo, precio) VALUES
(
  'INIM PREVIDIA-C-REPR Repetidora paneles direccionables',
  'C-REPER REPETIDORA PARA PANELES PREVIDIA COMPACT PREVIDIA MAX Y PREVIDIA ULTRAVOX VERSION ESTANDAR, COLOR ROJO, CUMPLIMIENTO EN54',
  NULL,
  NULL,
  
  924249,1
),
(
  'INIM PREVIDIA-C-REPER Repetidora canal extincion',
  'C-REPER REPETIDORA PARA PANELES PREVIDIA COMPACT PREVIDIA MAX Y PREVIDIA ULTRAVOX, VERSION DE INDICACION RELATIVA A UN CANAL DE EXTINCION, COLOR ROJO, CUMPLIMIENTO EN54',
  NULL,
  NULL,
  
  1036085,1
),
(
  'INIM PREVIDIA-C050SZER Panel direccionable extincion',
  'PANEL DETECCION DE INCENDIO DIRECCIONABLE 1 LOOP (64 DISPOSITIVOS)+1 CH EXTINCION+LED DE ZONAS INCLUYE APP CLOUD PARA MONITOREO Y CONTROL REMOTO TOUCH SCREEN CUMPLIMIENTO EN54',
  NULL,
  NULL,
  
  3192996,1
),
(
  'INIM IFMEXT Modulo extincion gas',
  '** Existencia Única ** MODULO PARA EXTINCION POR AGENTE LIMPIO (GAS) DIRECCIONABLE COMPATIBLE CON PREVIDA MAX Y ULTRAVOX USAR CON FPMEXT-G HASTA 24 POR PANEL CUMPLIMIENTO UL/EN54',
  NULL,
  NULL,
  
  673367,1
),
(
  'INIM FPMEXT-G Modulo led señalizacion extincion',
  '** Existencia Única ** MODULO LED PARA SEÑALIZACION CON 5 CH DE EXTINCION (USAR CON IFMEXT) COMPATIBLE CON PREVIDA MAX Y ULTRAVOX',
  NULL,
  NULL,
  
  918079,1
);


-- 50 - 81
INSERT INTO producto (producto, descripcion, id_categoria, id_subcategoria, costo, precio) VALUES

-- MODULOS EXTINCION
(
  'INIM IFMEXT Modulo extincion gas',
  '** Existencia Única ** MODULO PARA EXTINCION POR AGENTE LIMPIO (GAS) DIRECCIONABLE COMPATIBLE CON PREVIDA MAX Y ULTRAVOX USAR CON FPMEXT-G HASTA 24 POR PANEL CUMPLIMIENTO UL/EN54',
  NULL, NULL,  673367,1
),
(
  'INIM FPMEXT-G Modulo LED extincion',
  '** Existencia Única ** MODULO LED PARA SEÑALIZACION CON 5 CH DE EXTINCION (USAR CON IFMEXT) COMPATIBLE CON PREVIDA MAX Y ULTRAVOX',
  NULL, NULL, 918079,1
),

-- PANELES AUDIO EVACUACION
(
  'INIM PREVIDIA-ULTRAVOX-R Panel direccionable audio',
  'PANEL DE DETECCION DE INCENDIOS DIRECCIONABLE CON AUDIO EVACUACION Y VOCEO HASTA 16 LOOPS 30 AMPLIFICADORES 1 MATRIZ DE AUDIO SERVIDOR Y APP DE AUDIO CUMPLIMIENTO EN54',
  NULL, NULL, 15542322,1
),

-- MODULOS EXPANSION PREVIDIA
(
  'INIM IFMNET Modulo RS485',
  'MODULO RS485 PARA CONEXION DE PANELES PREVIDIA MAX',
  NULL, NULL,  1304698,1
),
(
  'INIM INFEIN1PIFMLAN Modulo LAN',
  'MODULO LAN PARA PANELES PREVIDIA MAX PARA HABILITAR FUNCIONES TCP/IP AVANZADAS',
  NULL, NULL,  1607898,1
),
(
  'INIM INFEIN1PIFM2L Expansor lazos',
  'MODULO EXPANSOR DE DOS LAZOS PARA PANELES PREVIDIA MAX HASTA 240 DISPOSITIVOS POR LAZO',
  NULL, NULL,  2348334,1
),

-- DETECTORES HUMO DIRECCIONABLES
(
  'INIM ED100 Detector humo direccionable',
  'DETECTOR DE HUMO OPTICO 2 HILOS DIRECCIONAL SERIE ENEA SENSIBILIDAD CONFIGURABLE, CUMPLIMIENTO EN54 Y UL PARA PANELES PREVIDIA COMPACT PREVIDIA MAX Y PREVIDIA ULTRAVOX',
  NULL, NULL, 104023,1
),
(
  'INIM INFDIN4AED100 Detector humo ENEA',
  'DETECTOR DE HUMO OPTICO DIRECCIONAL SERIE ENEA SENSIBILIDAD CONFIGURABLE, CUMPLIMIENTO EN54 Y UL PARA PANELES PREVIDIA COMPACT Y PREVIDIA MAX',
  NULL, NULL, 136046,1
),

-- DETECTORES TERMICOS
(
  'INIM INFDIN4AED200 Detector termico',
  'DETECTOR TERMICO DIRECCIONABLE SERIE IRIS SENSIBILIDAD CONFIGURABLE  CUMPLIMIENTO EN54 Y UL PARA PANELES PREVIDIA COMPACT Y PREVIDIA MAX',
  NULL, NULL, 130911,1
),
(
  'INIM ED200 Detector termico 2 hilos',
  'DETECTOR TERMICO 2 HILOS DIRECCIONABLE SERIE IRIS SENSIBILIDAD CONFIGURABLE  CUMPLIMIENTO EN54 Y UL PARA PANELES PREVIDIA COMPACT Y PREVIDIA MAX',
  NULL, NULL, 133958,1
),

-- DETECTORES DUALES
(
  'INIM ED300 Detector optico termico',
  'DETECTOR OPTICO/TERMICO 2 HILOS DIRECCIONABLE SERIE IRIS SENSIBILIDAD Y MODO DE OPERACIÓN CONFIGURABLE CUMPLIMIENTO EN54 Y UL PARA PANELES PREVIDIA COMPACT PREVIDIA MAX Y PREVIDIA ULTRAVOX',
  NULL, NULL,  160840,1
),

-- ESTACION MANUAL
(
  'INIM WCP0020 Cubierta pulsador',
  'CUBIERTA TRANSPARENTE PARA EVITAR ACTIVACION ACCIDENTAL COMPATIBLE CON PULSADORES EC0020 E IC0020',
  NULL, NULL, 4641,1
),
(
  'INIM EC0020 Estacion manual direccionable',
  'ESTACION MANUAL (PULSADOR) DE ALARMA DIRECCIONABLE REARMABLE CON LLAVE, CUMPLIMIENTO EN54',
  NULL, NULL, 226123,1
),

-- SIRENAS DIRECCIONABLES
(
  'INIM ES2021RE Sirena direccionable',
  'SIRENA OPTICO/ACUSTICA DIRECCIONABLE MAX 101DB A 1M PARA INTERIOR Y EXTERIOR IP65 CUMPLIMIENTO EN54',
  NULL, NULL, 245538,1
),
(
  'INIM ES2050RE Sirena direccionable voz',
  'SIRENA OPTICO/ACUSTICA DIRECCIONABLE MAX 100DB A 1M AVISO DE VOZ PARA INTERIOR Y EXTERIOR IP65 CUMPLIMIENTO EN54 PARA PANELES PREVIDIA MAX PREVIDIA COMPACT Y PREVIDIA ULTRAVOX',
  NULL, NULL, 309566,1
),

-- FUENTES DE PODER
(
  'INIM IPS24060GV1 Fuente 24V 1.5A',
  'FUENTE DE ALIMENTACIÓN DE 24V Y 1,5A 2 SALIDAS, SOPORTA 2 BATERIAS SIN CAJA. SOPORTA HASTA 30 SIRENAS ESTROBOSCOPICAS',
  NULL, NULL,  185895,1
),
(
  'INIM IPS24160GV1 Fuente 24V 4A',
  'FUENTE DE ALIMENTACION IPS24160G 24V/4A/160W, SOPORTA HASTA 80 SIRENAS ESTROBOSCOPICAS',
  NULL, NULL,  421515,1
),
(
  'INIM BPS24060GV1 Fuente gabinete',
  'FUENTE DE ALIMENTACIÓN DE 24V Y 1,5A  CON GABINETE INIM, CE, SOPORTA 2 BATERIAS, SOPORTA HASTA 30 SIRENAS ESTROBOSCOPICAS',
  NULL, NULL,  469806,1
),
(
  'INIM SPS24060GV1 Fuente LCD',
  'FUENTE DE ALIMENTACIÓN DE 24V Y 1,5A  CON TECLADO Y PANTALLA LCD, EN54, 3 SALIDAS, SOPORTA 2 BATERIAS, SOPORTA HASTA 30 SIRENAS ESTROBOSCOPICAS',
  NULL, NULL,  819535,1
),

-- MODULOS DE LAZO
(
  'INIM INFMIN4AEU311S Micro modulo salida',
  'MICRO MODULO SALIDA ANALOGICO E311S',
  NULL, NULL,  124503,1
),
(
  'INIM EM110 Modulo entrada',
  'MODULO DIRECCIONABLE CON 1 ENTRADA SUPERVISADA',
  NULL, NULL, 156163,1
),
(
  'INIM EM312SR Modulo entrada salida',
  'MODULO DIRECCIONABLE CON 1 ENTRADA SUPERVISADA Y 1 SALIDA SUPERVISADA/RELE HASTA 240 DIRECCIONES',
  NULL, NULL, 214461,1
),
(
  'INIM EM304R Modulo analogico',
  'MODULO ANALOGO DIRECCIONABLE CON 4 SALIDAS DE CONTACTO SECO',
  NULL, NULL, 508147,1
);

INSERT INTO producto (producto, descripcion, id_categoria, id_subcategoria, costo, precio) VALUES

-- HERRAMIENTA CONFIGURACION
(
  'INFAIN1PEITK2000 Herramienta configuracion sensores inim',
  'HERRAMIENTA PARA CONFIGURAR SENSORES IRIS/ENEA INCLUYE MALETIN Y CONECTORES',
  NULL, NULL,  783394,1
),

-- CAMPANA MOTORIZADA
(
  'ISC010 Campana motorizada 95db inim',
  'CAMPANA MOTORIZADA DE 95DB A 19 A 28VCC BAJO CONSUMO CON DIODO DE POLARIZACION IP21',
  NULL, NULL, 155550,1
);



---
--COFEM
--

INSERT INTO producto (producto, descripcion, id_categoria, id_subcategoria, costo, precio) VALUES

-- SENSORES CONVENCIONALES OPTICO TERMICO
(
  'A30XHA Detector optico termico direccionable cofem',
  'DETECTOR OPTICO TERMICO ANALOGICO DIRECCIONABLE. NO INCLUYE BASE',
  NULL, NULL,  96419,1
),

(
  'ZYR Central repetidora incendio cofem',
  'CENTRAL REPETIDORA PARA LYON/ZAFIR Y COMPACT LYON. MAXMO 15 REPETIDORES DE 4 HILOS',
  NULL, NULL,  1674573,1
),

-- SENSORES CONVENCIONALES OPTICO HUMO
(
  'A30XHAS Detector humo optico direccionable cofem',
  'DETECTOR DE HUMO ÓPTICO ANÁLOGICO-DIRECCIONABLE CON AUTOCOMPESENACION',
  NULL, NULL,  113365,1
),

-- SENSORES DIRECCIONABLES TERMICOS
(
  'A30XTA Detector termico direccionable cofem',
  'DETECTOR TERMICO ANALOGICO DIRECCIONABLE, CON FUNCION TERMOVELOCIMETRICA.',
  NULL, NULL,  83305,1
),

-- MODULOS DIRECCIONABLES
(
  'MSTAY Modulo master direccionable cofem',
  'MÓDULO MASTER ANALÓGICO MICROPROCESADO Y DIRECCIONABLE  PARA MANEJO DE SEÑALES EXTERNAS.',
  NULL, NULL,  113633 ,1
),

(
  'MDA1Y Modulo direccionable 1 rele cofem',
  'MÓDULO MICROPROCESADO Y DIRECCIONABLE (CON AISLADOR DE CORTOCIRCUITO) PARA DISPARO DE  1 RELE',
  NULL, NULL,  181135 ,1
),

(
  'MDA2Y Modulo direccionable 2 reles cofem',
  'MÓDULO MICROPROCESADO Y DIRECCIONABLE PARA DISPARO DE  2 RELES',
  NULL, NULL, 199503 ,1
),

-- DETECTOR AUTONOMO GAS
(
  'DAGR110 Detector autonomo gas 110vac cofem',
  'DETECTOR AUTÓNOMO DE GAS CON ALARMA ACÚSTICA, SALIDA DE RELES. TENSIÓN DE TRABAJO 110 VAC',
  NULL, NULL,  143139,1
),

(
  'DAGR24 Detector autonomo gas 24vdc cofem',
  'DETECTOR AUTÓNOMO DE GAS CON ALARMA ACÚSTICA, SALIDA DE RELES. TENSIÓN DE TRABAJO 24 VDC.',
  NULL, NULL, 150302,1
),

(
  'DAGR12 Detector autonomo gas 12vdc cofem',
  'DETECTOR AUTÓNOMO DE GAS CON ALARMA ACÚSTICA, SALIDA DE RELES. TENSIÓN DE TRABAJO 12 VDC',
  NULL, NULL,  167093,1
),

-- BASE
(
  'A30XZO Base baja detectores incendio cofem',
  'BASE BAJA PARA DETECTORES DE DETECCIÓN DE INCENDIOS DE LA GAMA A30',
  NULL, NULL, 9460,1
),

-- AISLADOR DE BUCLE
(
  'KABY Zocalo aislador de bucle cofem',
  'ZÓCALO AISLADOR DE BUCLE.',
  NULL, NULL,  120683,1
),

-- ACCESORIOS
(
  'KITMEY Kit conexion ethernet central cofem',
  'KIT PARA CONEXION CENTRAL LYON ETHERNET CONVERTIDOR 485 INTERNET',
  NULL, NULL,  1220154,1
);


INSERT INTO producto (producto, descripcion, id_categoria, id_subcategoria, costo, precio)
VALUES (
  'DHI-HY-SA21A-W2 Detector humo inalambrico dahua',
  'DETECTOR DE HUMO INALÁMBRICO. SENSOR FOTOELÉCTRICO DOBLE CÁMARA. SIRENA INTERNA 85DB.',
  NULL,
  NULL,
  148678,
  1
);
